/* ---------- Directorio de la casa ----------
   Quién trabaja dónde. Dos fuentes:

   · CIIP: "Listado General correos activos", 176 personas (177 filas del
     listado, menos una duplicada por error de captura).
   · Marca País: "Listado de los correos" del Instituto (18/08/2026), 48
     de sus 50 personas —quedaron fuera dos sin correo en ese listado, sin
     forma de registrar una cuenta—, cruzadas por cédula contra el corte de
     control de acceso del 27/07/2026 para recuperar gerencia, piso,
     oficina y cargo: ese Excel solo traía cédula, nombre y el Gmail.

   224 personas en total. Sirve para que nadie escriba su gerencia ni su
   cargo: escribe su nombre, se elige de la lista y el resto se llena solo.

   NO LLEVA CÉDULA, a propósito. La versión anterior sí la llevaba, con esta
   nota: "vale mientras esto viva en la red interna; el día que el sitio salga
   a internet, esta columna hay que sacarla". El sitio ya salió a internet
   (https://soporte-ciip.vercel.app, público, sin clave), así que se saca
   ahora: la Hoja de Servicio sigue pudiendo llevar cédula, pero la escribe
   quien pide, no la sirve este archivo a cualquiera que abra la página.

   Piso y oficina quedan vacíos para el CIIP —ese listado no los tenía— y
   puestos para casi todo Marca País, recuperados del cruce. Quien no los
   tenga los escribe a mano, como si no apareciera en la lista.

   No lleva correo ni contraseña, ni falta que hacen aquí: los correos van
   en gtic.correos_permitidos (ver sql/), que decide quién puede REGISTRARSE,
   no quién aparece al elegirse de esta lista — son dos preguntas distintas,
   y una de las dos sí puede vivir en un archivo que el navegador de
   cualquiera descarga sin clave. La otra, nunca.
   Prefijo: DIRECTORIO. */
const DIRECTORIO = [
  {nombre:'Adrian Enrique Figueroa Barrios', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Aimee Estefania Ruiz Galavis', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Airuth del Valle Irazabal Hurtado', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Alcides Alejandro Robles Gordillo', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Alejandro Enrique Puglia Costas', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Presidente'},
  {nombre:'Alexander Daniel Blanco Ladino', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Alfredo Antonio Carrera Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Amarielys Gisel Gonzalez Muñoz', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Ana Maria Arraiz de Conde', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Ana Maria Villarroel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Andry Jesus Tovar Cabrera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Andrymar Mileydys Arellano Olivier', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Angelica Maria Ramirez Arellano', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Anghela Jacqueline Andrius Dávila Márquez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Aquiles Augusto Figueroa Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Barbara Yaismely Petterson Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Barbara Yaneth Depablos Torres', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Bracho Angel', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Carlos Alberto Belisario Silva', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Carlos Alejandro Garcia Alvarez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Carlos Daniel Torres Rodriguez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Carlos Eduardo Barreto Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Galindo Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Perea Rangel', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carlos Enrique Manzano Kossik', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Carlos Manuel Rodriguez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carmen Oviedo Urrutia', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carolina Forgione Franco', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Carolina Isabel Vargas Julio', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Chuaima Felipe Salas Camacho', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Dailyn Alejandra Romero Ardiles', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Dan Keisdert Moreno', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Danger Luis Rivero Ruiz', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Daniel Alberto Yepes Rivas', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Danna Alexandra Burguillos Díaz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Danny Joel Aponte Aponte', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Danyil Rafael Lugo Celis', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Deiber Jose Francisco Sella Dominguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Deinyelbert Jocksaniel Rodriguez Sarmiento', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Desiree Alejandra Cordero Lobo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Diana Carolina Bracho Indriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Dilia Yamilet Serrano Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Divarlys Nakarith Ocando Faneyte', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Douglas Emilio Prin Pereira', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Eddy Yolanda Peña de Granado', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Edward Jhonny Gonzalez', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Elias Josue Martinez Luque', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Eliub Ricardo Solorzano Perez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Ellius Enrique Rios Hernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Elys Daniel Martinez Zambrano', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Emely Miraidy Garcia Osuna', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Emely Nazaret Escalona Correa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Ericka Dubraska Flores Acevedo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Fabiola de los Angeles Martinez Duque', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Especialista'},
  {nombre:'Felix Armando Arraiz Planchart', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Franciel Jesus Rodriguez Bernal', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Francy Yusney Rincon', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Franklin David Reyes Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Franklin Nayit Acosta Angarita', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Fravia Vanessa Marquez de Fernandez', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Frenddy Enrique Santana Buitriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Gabriel Ramon Reyes Rangel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Gabriela Carolina de los Angeles Brito Gómez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Geraldyn de los Angeles Lopez Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'German Javier Gerardino Diaz', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Guillermo Alexander Torres', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Gustavo Jose Zuñiga', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Hector Jose Bravo Osuna', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Hedwing Jose Gutierrez Blanco', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Hernan Enrique Marcano Oberto', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Hilda Anais Newman Mijares', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Imari del Valle Vasquez Capote', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Isabel Maria Peñaranda', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Isbelis Marielys Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Isolimar Coromoto Sanchez Fernandez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Ivan Arley Llanos', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Jackelyn Josefina Bermejo', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Jesly Oriana Baez Macedo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Jessica Erlynes Rodriguez Alvarez', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jesus Antonio Arellano Natera', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Jipson Jesus Granadillo Albarran', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Joel Roman Aguilar Castro', gerencia:'VICEPRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Johanna Betzabeth De Almada Nieves', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jojan Jose Valbuena Garcia', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Jonathan Avisai Morales Martínez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jonathan George Urbina Fernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Jose Gregorio Hernández Villegas', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Jose Gregorio Muñoz Rodriguez', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Jose Manuel Barrios Riera', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Jose Rafael Olivares Rodriguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Juber Anulfo Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Julmar Enrique Moron Vasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Karelys Juliett Sanchez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Karen de Jesus Perez Muñoz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Karla Rosibel Sierra Palacios', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:''},
  {nombre:'Katiuska Elizabeth Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Katiuska del Valle Diaz Yanez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Kristina Dugnas Sulcas', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Layla Anabery Gonzalez Varela', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Leomary Andreina Malave Moreno', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Loisbeth Mariana Corvos Arismendi', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Lord Yolindria Guacache Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Lucia Sampaio Martins', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luigersy Enrique Correa Mendez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Luis Alberto Ortega', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luis Alejandro Flores Gonzalez', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Luis Leopoldo Narvaez Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Luis Miguel Ferrer Belgoderi', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luis Vicente Garcia Lamas', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Mairin Celeste Camacho Escobar', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Manuel Eduardo Rodriguez Pereira', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Marbelis Eva Davila Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Marco Antonio Magallanes Grillet', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Consultor Jurídico'},
  {nombre:'Maria Emilia Torres Bonten', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maria Fernanda Ruiz Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Maria Jose Hernandez Morales', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maria Patricia Ferreira Mendoza', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Maria Pia Savoia Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Maria Rosana Rodriguez Guzman', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Maribella Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Mariela Andrea Curvelo Hernández', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Marienny Daniela Santos Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Marilin Andreina Nuñez Arraiz', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Marinel Luzey Colmenares Blanco', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Martin Rafael Jimenez Calvo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Marysabel Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maurelys Estefani Gonzalez Mosquera', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Mazuris Jiraly Azocar Benitez', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Migdalia Isabel Sanz Vaamondes', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Miguel Angel Cardenas Yepez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Miguel Angel Espinoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Milagros de Jesus Torres Gonzalez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Morella Carmona de Hernandez', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Nahiry de Jesus Alcina Velasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Nancy del Carmen Tovar Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Nathalia Yusmairi Guillen Lopez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Nelly del Carmen Rios Deal', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Nelson Jose Berrios', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Noraima del Milagro Coy Parra', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Oriana Gabriela Reina Mayora', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Oriana Patricia Perez Cabello', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Orlando Jose Yanez Saez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Rahelenys Josue Burgos Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Rayda Ysabel Vera Parra', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Auditor Interno'},
  {nombre:'Regulo Antonio Ramirez Yanez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Renny Moises Poleo Gascon', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Ricardo Jesus La Cruz Garcia', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Romelis Maria Viña Garcia', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Ronnie Percak Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Rosbely del Carmen Bracho Indriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Rosmary Mariana Pantoja Blanco', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Samy Emerson Osuna Mendoza', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Saray Ailemar Verdu Aragot', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Saskia Catheryn Victoria Calderon Veliz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Saudy Coromoto Contreras', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Solangel Nailyn Suinagas Rada', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Solisver Coromoto Urbaez de Sandoval', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Treizen Guanipa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Veruska Vanessa Vizcaya Castillo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Vicente Paul Castillo Castellanos', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Viviana Isabel Cuello Pino', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Wilfredo Niebles Villasmil', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'William Alfredo Castillo Bolle', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Xiomara Sandoval Narvaez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Yajaira Coromoto Pinto Diaz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Yarizmit Gheinsy Herrera Medina', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yelinet Alexandra Ibarra Isturiz', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Yelitza Yatzyl Armas Liendo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Yenaida Fagundez Vera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yender Yuhuare Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Yeniffer del Carmen Betancourt', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Supervisor'},
  {nombre:'Yesenia Janerys Martinez Escalona', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Yessica Carolina Gomez Solorzano', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Yoliskar de los Angeles Diaz Velasquez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yosmary Vanesa Valero Paredes', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Yuraima Karina Martinez Diaz', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Especialista'},

  /* Marca País, del "Listado de los correos" del Instituto Marca País
     (18/08/2026): 48 personas —de 50, quedaron fuera Manuel Marcial y
     Miguel Angel Zapata Torres, sin correo en ese listado y por lo tanto
     sin forma de registrar una cuenta—, cruzadas por cédula contra el
     corte de control de acceso del 27/07/2026 para recuperar gerencia,
     piso, oficina y cargo. Ese Excel no traía esos datos, solo cédula,
     nombre y el Gmail personal (ver gtic.correos_permitidos).

     Cuatro no cruzaron —dadas de alta después del corte de acceso, o con
     la cédula mal tecleada en alguno de los dos listados— y se agregan
     solo con el nombre, sin gerencia: el formulario ya sabe llenar ese
     hueco a mano, igual que con piso y oficina. */
  {nombre:'Adriana Carolina Sánchez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Administrativo'},
  {nombre:'Aidyn Paulina Moreno Escalona', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Aimara Alexandra Martínez Cerezo', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Alexis Manuel Velásquez Cañate', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Andrea Martinez Carpio', gerencia:'PRESIDENCIA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Antonio José Gregorio Ramos Martinez', gerencia:'CONSULTORÍA JURÍDICA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'Arizay Ismaelyn Eekhaut Molina', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Aseadora'},
  {nombre:'Astrid Karina Uribe Sánchez', gerencia:'GERENTE DE ARTICULACIÓN ESTRATÉGICA PARA EL IMPULSO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente de Articulación'},
  {nombre:'Carlos Alberto Durán Sánchez', gerencia:'GERENTE DE ARTICULACIÓN ESTRATÉGICA PARA EL IMPULSO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Darwin Nivaldo Zuarce', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'David Alexander Guerrero Figueroa', gerencia:'', piso:'', oficina:'', cargo:''},
  {nombre:'Dayana Veronica Chediak Kasrin', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Dayana del Carmen Lara Cornielis', gerencia:'AUDITORÍA INTERNA (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Dayannis del Valle Alvárez Millán', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Edgar Mata', gerencia:'', piso:'', oficina:'', cargo:''},
  {nombre:'Edignorelia Valbuena Morales', gerencia:'GERENCIA GENERAL DE REGULACIÓN, USO Y SEGUIMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Institucional'},
  {nombre:'Edward Eduardo Lunar', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Administrativo'},
  {nombre:'Elizabeth Mendoza', gerencia:'GERENCIA GENERAL DE REGULACIÓN, USO Y SEGUIMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General de Regulación'},
  {nombre:'Ender José Cobarrubia', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Erich Nailen Escalante de Dulcey', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Gabriela Liendo Paredes', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Genesis Ivanova González Dicuru', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Institucional'},
  {nombre:'Ivette Andreina Dominguez Gomez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Jhoanyeli Nazareth González González', gerencia:'', piso:'', oficina:'', cargo:''},
  {nombre:'Jhon Manuel Gutiérrez Marín', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Joeli Vanessa Martínez Welma', gerencia:'GERENCIA GENERAL (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Jonel Manuel Ortiz Denis', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'José Angel Guerra', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Judelys Daniela Romero Espinoza', gerencia:'GERENCIA GENERAL (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General'},
  {nombre:'Karen Luisana Monsalve Cedres', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Lisbeth Amparo Padilla Arnal', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Maritza Beatriz Nadales', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Institucional'},
  {nombre:'Michelangely Josefina Griffith Añazco', gerencia:'GERENCIA DE ATENCIÓN CIUDADANA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente'},
  {nombre:'Niki Benjamin Herrera Gómez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Ninoska García Perez', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'Niurka Carolina Quintero Contreras', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Gerente'},
  {nombre:'Omar Rogelio Garcia', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Institucional'},
  {nombre:'Patricia Carolina Miranda Villamizar', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Ramon Antonio Narvaez Flores', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General de Promociones'},
  {nombre:'Manuel Alexander Reyes Rodriguez', gerencia:'', piso:'', oficina:'', cargo:''},
  {nombre:'Ruben Ernesto Moreno Vasquez', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Gerente'},
  {nombre:'Stefany Valentina Mendible Ramírez', gerencia:'PRESIDENCIA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Tana Valentina Vásquez Rojas', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Administrativo'},
  {nombre:'Victor José Mosalve Rodríguez', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Chofer'},
  {nombre:'Vincent Orlando Oropeza', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Yaneth Mercedes Duarte de Ortiz', gerencia:'GERENCIA DE PLANIFICACIÓN Y PRESUPUESTO (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Yannely Dominguez Salcedo', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Gerente'},
  {nombre:'Yarumi Tarazon Betancourt', gerencia:'GERENCIA DE PLANIFICACIÓN Y PRESUPUESTO (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Gerente'},
];

/* Busca por nombre exacto, sin distinguir mayúsculas, espacios de sobra ni
   tildes: "Jesus" y "Jesús" son el mismo nombre mal tecleado, no dos personas
   distintas, así que exigirle la tilde exacta solo rompía el auto-completado
   sin evitar ningún homónimo real. Sigue siendo el nombre completo, letra por
   letra salvo el acento: no se adivina por parecido. */
function directorioBuscar(nombre){
  const limpiar = s => String(s || '').trim().toLowerCase().replace(/\s+/g, ' ')
    .normalize('NFD').replace(/\p{Diacritic}/gu, '');
  const n = limpiar(nombre);
  if(!n) return null;
  return DIRECTORIO.find(p => limpiar(p.nombre) === n) || null;
}
