/* ---------- Directorio de la casa ----------
   Quién trabaja dónde. Sale del listado de control de acceso del CIIP con
   corte del 27 de julio de 2026 —el que lleva Seguridad—, que es el censo real
   del personal, no una reconstrucción a partir de papeles viejos.

   Sirve para que nadie escriba su gerencia, su piso ni su oficina: escribe su
   nombre, se elige de la lista y el resto se llena solo.

   Están el CIIP y Marca País. VENAPP queda fuera: es otro ente y no lo atiende
   esta gerencia.

   NO LLEVA CÉDULA, aunque el listado la trae. Este archivo viaja al navegador
   de cualquiera que abra la página, que no pide clave; publicar ahí la cédula
   de 224 compañeros sería regalarlas. El campo sigue siendo opcional en la
   planilla y lo escribe cada quien.

   Tampoco lleva nada de vehículos ni horarios: no hace falta para pedir un
   soporte.

   Cuando alguien mande una solicitud con datos distintos —porque se mudó de
   oficina o cambió de gerencia—, mandan los que escribió: esta lista es un
   punto de partida, no una autoridad. Se corrige a mano cuando Seguridad
   emita un corte nuevo.
   Prefijo: DIRECTORIO. */
const DIRECTORIO = [
  {nombre:'Adriana Carolina Sánchez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Administrativo'},
  {nombre:'Aidyn Paulina Moreno Escalona', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Aimara Alexandra Martínez Cerezo', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Aimee Estefania Ruiz Galavis', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Profesional'},
  {nombre:'Airuth del Valle Irazabal Hurtado', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Alejandro Enrique Puglia Costas', gerencia:'PRESIDENCIA', piso:'9', oficina:'', cargo:'Presidente'},
  {nombre:'Alexander Daniel Blanco Ladino', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'8', oficina:'8-02', cargo:'Coordinador'},
  {nombre:'Alexis Manuel Velásquez Cañate', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Alfredo Antonio Carrera Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Gerente'},
  {nombre:'Amarielys Gisel Gonzalez Muñoz', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Profesional'},
  {nombre:'Ana Maria Arraiz de Conde', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Bachiller'},
  {nombre:'Ana Maria Villarroel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Andrea Martinez Carpio', gerencia:'PRESIDENCIA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Andreina Tarazón Bolívar', gerencia:'PRESIDENCIA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Presidenta'},
  {nombre:'Andry Jesus Tovar Cabrera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Profesional'},
  {nombre:'Andrymar Mileydys Arellano Olivier', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-04', cargo:'Asistente Ejecutivo'},
  {nombre:'Angelica Maria Ramirez Arellano', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-03', cargo:'Bachiller'},
  {nombre:'Anghela Jacqueline Andrius Davila Marquez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Annelin del Carmen Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Gerente'},
  {nombre:'Antonio José Gregorio Ramos Martinez', gerencia:'CONSULTORÍA JURÍDICA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'Aquiles Augusto Figueroa Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Bachiller'},
  {nombre:'Arizay Ismaelyn Eekhaut Molina', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Aseadora'},
  {nombre:'Astrid Karina Uribe Sánchez', gerencia:'GERENTE DE ARTICULACIÓN ESTRATÉGICA PARA EL IMPULSO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente de Articulación'},
  {nombre:'Barbara Yaismely Petterson Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Profesional'},
  {nombre:'Barbara Yaneth Depablos Torres', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carlos Alberto Belisario Silva', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Profesional'},
  {nombre:'Carlos Alberto Durán Sánchez', gerencia:'GERENTE DE ARTICULACIÓN ESTRATÉGICA PARA EL IMPULSO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Carlos Alejandro Garcia Alvarez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Carlos Daniel Torres Rodriguez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Carlos Eduardo Barreto Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Galindo Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Perea Rangel', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Bachiller'},
  {nombre:'Carlos Enrique Manzano Kossik', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Gerente'},
  {nombre:'Carlos Manuel Rodriguez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-06', cargo:'Bachiller'},
  {nombre:'Carmen Oviedo Urrutia', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Bachiller'},
  {nombre:'Carolina Forgione Franco', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Tecnico'},
  {nombre:'Carolina Isabel Vargas Julio', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Asesor Tecnico'},
  {nombre:'Chuaima Felipe Salas Camacho', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Dailyn Alejandra Romero Ardiles', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Tecnico'},
  {nombre:'Dan Keisdert Moreno', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Bachiller'},
  {nombre:'Danger Luis Rivero Ruiz', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Bachiller'},
  {nombre:'Daniel Alberto Yepes Rivas', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'8', oficina:'8-02', cargo:'Profesional'},
  {nombre:'Danna Alexandra Burguillos Díaz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Asesor Tecnico'},
  {nombre:'Danny Joel Aponte Aponte', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'4', oficina:'4-07', cargo:'Gerente'},
  {nombre:'Danyil Rafael Lugo Celis', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Obrero Certificado'},
  {nombre:'Darwin Nivaldo Zuarce', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'Dayana del Carmen Lara Cornielis', gerencia:'AUDITORÍA INTERNA (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Dayana Veronica Chediak Kasrin', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Dayannis del Valle Alvárez Millán', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Deiber Jose Francisco Sella Dominguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Bachiller'},
  {nombre:'Deinyelbert Jocksaniel Rodriguez Sarmiento', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Bachiller Iii - Vii'},
  {nombre:'Desiree Alejandra Cordero Lobo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-04', cargo:'Bachiller'},
  {nombre:'Diana Carolina Bracho Indriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Tecnico'},
  {nombre:'Dilia Yamilet Serrano Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Gerente'},
  {nombre:'Divarlys Nakarith Ocando Faneyte', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Gerente'},
  {nombre:'Douglas Emilio Prin Pereira', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Tecnico'},
  {nombre:'Eddy Yolanda Peña de Granado', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Gerente'},
  {nombre:'Edgar Alejandro Bolivar Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Obrero Certificado'},
  {nombre:'Edignorelia Valbuena Morales', gerencia:'GERENCIA GENERAL DE REGULACIÓN, USO Y SEGUIMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Institucional'},
  {nombre:'Edward Eduardo Lunar', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Administrativo'},
  {nombre:'Edward Jhonny Gonzalez', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'2', oficina:'2-03', cargo:'Coordinador'},
  {nombre:'Elias Josue Martinez Luque', gerencia:'PRESIDENCIA', piso:'9', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Eliub Ricardo Solorzano Perez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Gerente'},
  {nombre:'Elizabeth Mendoza', gerencia:'GERENCIA GENERAL DE REGULACIÓN, USO Y SEGUIMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General de Regulación'},
  {nombre:'Ellius Enrique Rios Hernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Elys Daniel Martinez Zambrano', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Gerente'},
  {nombre:'Emely Miraidy Garcia Osuna', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-06', cargo:'Tecnico'},
  {nombre:'Emely Nazaret Escalona Correa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Ender José Cobarrubia', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Enry Josue Duran', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-07', cargo:'Gerente General'},
  {nombre:'Erich Nailen Escalante de Dulcey', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Ericka Dubraska Flores Acevedo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Gerente'},
  {nombre:'Felix Armando Arraiz Planchart', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Profesional'},
  {nombre:'Franklin David Reyes Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Bachiller'},
  {nombre:'Franklin Nayit Acosta Angarita', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Bachiller'},
  {nombre:'Fravia Vanessa Marquez de Fernandez', gerencia:'PRESIDENCIA', piso:'8', oficina:'8-02', cargo:'Asesor Profesional'},
  {nombre:'Frenddy Enrique Santana Buitrago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Gabriel Ramon Reyes Rangel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'8', oficina:'8-02', cargo:'Obrero Certificado'},
  {nombre:'Gabriela Carolina de los Angeles Brito Gomez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Gabriela Liendo Paredes', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Genesis Ivanova González Dicuru', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Institucional'},
  {nombre:'Geraldyn de los Angeles Lopez Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Asistente Ejecutivo'},
  {nombre:'German Javier Gerardino Diaz', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Coordinador'},
  {nombre:'Guillermo Alexander Torres', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Gustavo Jose Zuñiga', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Bachiller'},
  {nombre:'Hector Jose Bravo Osuna', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Coordinador'},
  {nombre:'Hedwing Jose Gutierrez Blanco', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Gerente'},
  {nombre:'Hernan Enrique Marcano Oberto', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Asesor Tecnico'},
  {nombre:'Herrera Medina Herrera Medina', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Profesional'},
  {nombre:'Hilda Anais Newman Mijares', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Imari del Valle Vasquez Capote', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Tecnico'},
  {nombre:'Isabel Maria Peñaranda', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Isbelis Marielys Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Isolimar Coromoto Sanchez Fernandez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Coordinador'},
  {nombre:'Ivan Arley Llanos', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Asesor Tecnico'},
  {nombre:'Ivette Andreina Dominguez Gomez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Jackelyn Josefina Bermejo', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Jesly Oriana Baez Macedo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-04', cargo:'Bachiller'},
  {nombre:'Jessica Erlynes Rodriguez Alvarez', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'8', oficina:'8-02', cargo:'Profesional'},
  {nombre:'Jesus Antonio Arellano Natera', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Gerente General'},
  {nombre:'Jhon Manuel Gutiérrez Marín', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Jipson Jesus Granadillo Albarran', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Bachiller'},
  {nombre:'Joel Roman Aguilar Castro', gerencia:'VICEPRESIDENCIA', piso:'9', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Joeli Vanessa Martínez Welma', gerencia:'GERENCIA GENERAL (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Johanna Betzabeth De Almada Nieves', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-06', cargo:'Profesional'},
  {nombre:'Jojan Jose Valbuena Garcia', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'8', oficina:'8-02', cargo:'Coordinador'},
  {nombre:'Jonathan Avisai Morales Martinez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Jonathan George Urbina Fernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Obrero Certificado'},
  {nombre:'Jonel Manuel Ortiz Denis', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'José Angel Guerra', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Jose Gerardo Avendaño Rumbos', gerencia:'DIRECTORIO', piso:'9', oficina:'', cargo:'Director Suplente'},
  {nombre:'Jose Gregorio Hernandez Villegas', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Gerente'},
  {nombre:'Jose Manuel Barrios Riera', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'4', oficina:'4-07', cargo:'Gerente General'},
  {nombre:'Jose Rafael Olivares Rodriguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Gerente'},
  {nombre:'Juber Anulfo Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Tecnico'},
  {nombre:'Judelys Daniela Romero Espinoza', gerencia:'GERENCIA GENERAL (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General'},
  {nombre:'Julmar Enrique Moron Vasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Gerente'},
  {nombre:'Karelys Juliett Sanchez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Profesional'},
  {nombre:'Karen de Jesus Perez Muñoz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Karen Luisana Monsalve Cedres', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Katiuska del Valle Diaz Yanez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Gerente General'},
  {nombre:'Katiuska Elizabeth Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Kleiner Oscar Herrera Rodriguez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'2', oficina:'2-01', cargo:'Pasante'},
  {nombre:'Kristina Dugnas Sulcas', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Gerente General'},
  {nombre:'Leomary Andreina Malave Moreno', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-06', cargo:'Gerente'},
  {nombre:'Leonel David Lacera Urdaneta', gerencia:'DIRECTORIO', piso:'9', oficina:'', cargo:'Director Principal'},
  {nombre:'Lisbeth Amparo Padilla Arnal', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Loisbeth Mariana Corvos Arismendi', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Asistente Ejecutivo'},
  {nombre:'Lord Yolindria Guacache Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-03', cargo:'Asesor Profesional'},
  {nombre:'Lourdes Bethase Moro', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Honorarios Profesionales'},
  {nombre:'Lucia Sampaio Martins', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Luigersy Enrique Correa Mendez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Bachiller Iii - Vii'},
  {nombre:'Luis Alberto Ortega', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-03', cargo:'Asesor Profesional'},
  {nombre:'Luis Alejandro Flores Gonzalez', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Bachiller'},
  {nombre:'Luis Leopoldo Narvaez Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Gerente'},
  {nombre:'Luis Miguel Ferrer Belgoderi', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Asesor Profesional'},
  {nombre:'Luis Vicente Garcia Lamas', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-06', cargo:'Profesional'},
  {nombre:'Maigualida Josefina Santil Guaima', gerencia:'GERENCIA GENERAL (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Mairin Celeste Camacho Escobar', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Profesional'},
  {nombre:'Manuel Alexander Reyes Rodriguez', gerencia:'GERENCIA DE PLANIFICACIÓN Y PRESUPUESTO (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Manuel Eduardo Rodriguez Pereira', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Asesor Profesional'},
  {nombre:'Marbelis Eva Davila Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Profesional'},
  {nombre:'Marco Antonio Magallanes Grillet', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-07', cargo:'Consultor Juridico'},
  {nombre:'Maria Emilia Torres Bonten', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Maria Fernanda Ruiz Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Maria Jose Hernandez Morales', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Profesional'},
  {nombre:'Maria Patricia Ferreira Mendoza', gerencia:'PRESIDENCIA', piso:'9', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Maria Pia Savoia Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Gerente'},
  {nombre:'Maria Rosana Rodriguez Guzman', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Bachiller Iii - Vii'},
  {nombre:'Maribella Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Profesional'},
  {nombre:'Mariela Andrea Curvelo Hernández', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Bachiller'},
  {nombre:'Mariela Josefina Rodriguez Peralta', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Asesor Profesional'},
  {nombre:'Marienny Daniela Santos Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Marilin Andreina Nuñez Arraiz', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'4', oficina:'4-07', cargo:'Tecnico'},
  {nombre:'Marinel Luzey Colmenares Blanco', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Maritza Beatriz Nadales', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Institucional'},
  {nombre:'Martin Rafael Jimenez Calvo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Asesor Profesional'},
  {nombre:'Marysabel Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Profesional'},
  {nombre:'Maurelys Estefani Gonzalez Mosquera', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Tecnico'},
  {nombre:'Mazuris Jiraly Azocar Benitez', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Profesional'},
  {nombre:'Michelangely Josefina Griffith Añazco', gerencia:'GERENCIA DE ATENCIÓN CIUDADANA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente'},
  {nombre:'Migdalia Isabel Sanz Vaamondes', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Gerente'},
  {nombre:'Miguel Angel Cardenas Yepez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Tecnico'},
  {nombre:'Miguel Angel Espinoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Miguel Angel Zapata Torres', gerencia:'CONSULTORÍA JURÍDICA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Consultor Jurídico'},
  {nombre:'Milagros de Jesus Torres Gonzalez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Asistente Ejecutivo'},
  {nombre:'Morella Carmona de Hernandez', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Profesional'},
  {nombre:'Nahiry de Jesus Alcina Velasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Tecnico'},
  {nombre:'Nancy del Carmen Tovar Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Asesor Profesional'},
  {nombre:'Nathalia Yusmairi Guillen Lopez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Bachiller Iii - Vii'},
  {nombre:'Nelly del Carmen Rios Deal', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Nelson Jose Berrios', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Obrero General'},
  {nombre:'Niki Benjamin Herrera Gómez', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Honorarios Profesionales'},
  {nombre:'Ninoska García Perez', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Apoyo Profesional'},
  {nombre:'Niurka Carolina Quintero Contreras', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Gerente'},
  {nombre:'Noel Joaquin Gonzalez', gerencia:'DIRECTORIO', piso:'9', oficina:'', cargo:'Director Suplente'},
  {nombre:'Noraima del Milagro Coy Parra', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Asistente Ejecutivo'},
  {nombre:'Omar Rogelio Garcia', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Institucional'},
  {nombre:'Oriana Gabriela Reina Mayora', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Oriana Patricia Perez Cabello', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Bachiller'},
  {nombre:'Orlando Jose Yanez Saez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'3', oficina:'3-02', cargo:'Obrero Certificado'},
  {nombre:'Patricia Carolina Miranda Villamizar', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Técnico'},
  {nombre:'Paula Kristina Henao Vera', gerencia:'DIRECTORIO', piso:'9', oficina:'', cargo:'Director Principal'},
  {nombre:'Rahelenys Josue Burgos Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-03', cargo:'Gerente General'},
  {nombre:'Ramon Antonio Narvaez Flores', gerencia:'GERENCIA GENERAL DE PROMOCIÓN Y POSICIONAMIENTO DE LA MARCA PAÍS (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Gerente General de Promociones'},
  {nombre:'Rayda Ysabel Vera Parra', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Auditor Interno'},
  {nombre:'Renny Moises Poleo Gascon', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Profesional'},
  {nombre:'Ricardo Alberto Licett Palacios', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Institucional'},
  {nombre:'Ricardo Jesus La Cruz Garcia', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Asesor Profesional'},
  {nombre:'Romelis Maria Viña Garcia', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Ronnie Percak Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Asesor Profesional'},
  {nombre:'Rosbely del Carmen Godoy Briceño', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Rosmary Mariana Pantoja Blanco', gerencia:'AUDITORÍA INTERNA', piso:'2', oficina:'2-05', cargo:'Asistente Ejecutivo'},
  {nombre:'Ruben Ernesto Moreno Vasquez', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Gerente'},
  {nombre:'Samy Emerson Osuna Mendoza', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Asesor Profesional'},
  {nombre:'Saray Ailemar Verdu Aragot', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Profesional'},
  {nombre:'Saskia Catheryn Victoria Calderon Veliz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Profesional'},
  {nombre:'Saudy Coromoto Contreras', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Bachiller'},
  {nombre:'Solangel Nailyn Suinagas Rada', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'2', oficina:'2-03', cargo:'Coordinador'},
  {nombre:'Solisver Coromoto Urbaez de Sandoval', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Coordinador'},
  {nombre:'Stefany Valentina Mendible Ramírez', gerencia:'PRESIDENCIA (MARCA PAÍS)', piso:'3', oficina:'3-01', cargo:'Apoyo Profesional'},
  {nombre:'Tana Valentina Vásquez Rojas', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Administrativo'},
  {nombre:'Treizen Guanipa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-01', cargo:'Profesional'},
  {nombre:'Veruska Vanessa Vizcaya Castillo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'2', oficina:'2-04', cargo:'Asesor Profesional'},
  {nombre:'Vicente Paul Castillo Castellanos', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Profesional'},
  {nombre:'Victor José Mosalve Rodríguez', gerencia:'GERENCIA DE GESTIÓN ADMINISTRATIVA (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Chofer'},
  {nombre:'Vincent Orlando Oropeza', gerencia:'GERENCIA GESTIÓN COMUNICACIONAL (MARCA PAÍS)', piso:'3', oficina:'3-05', cargo:'Apoyo Profesional'},
  {nombre:'Viviana Isabel Cuello Pino', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'2', oficina:'2-01', cargo:'Profesional'},
  {nombre:'Wilfredo Niebles Villasmil', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Tecnico'},
  {nombre:'William Alfredo Castillo Bolle', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Gerente General'},
  {nombre:'Xiomara Sandoval Narvaez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Coordinador'},
  {nombre:'Yajaira Coromoto Pinto Diaz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'4', oficina:'4-09', cargo:'Asesor Tecnico'},
  {nombre:'Yaneth Mercedes Duarte de Ortiz', gerencia:'GERENCIA DE PLANIFICACIÓN Y PRESUPUESTO (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Apoyo Profesional'},
  {nombre:'Yannely Dominguez Salcedo', gerencia:'GERENCIA DE GESTIÓN HUMANA (MARCA PAÍS)', piso:'3', oficina:'3-04', cargo:'Gerente'},
  {nombre:'Yarumi Tarazon Betancourt', gerencia:'GERENCIA DE PLANIFICACIÓN Y PRESUPUESTO (MARCA PAÍS)', piso:'4', oficina:'4-06', cargo:'Gerente'},
  {nombre:'Yelinet Alexandra Ibarra Isturiz', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Yelitza Yatzyl Armas Liendo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'3', oficina:'3-02', cargo:'Tecnico'},
  {nombre:'Yenaida Fagundez Vera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'4', oficina:'4-05', cargo:'Profesional'},
  {nombre:'Yender Yuhuare Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero General'},
  {nombre:'Yeniffer del Carmen Betancourt', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-08', cargo:'Obrero Supervisor'},
  {nombre:'Yesenia Janerys Martinez Escalona', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'4', oficina:'4-02', cargo:'Gerente'},
  {nombre:'Yoliskar de los Angeles Diaz Velasquez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'1', oficina:'1-02', cargo:'Profesional'},
  {nombre:'Yosmary Vanesa Valero Paredes', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Yuraima Karina Martinez Diaz', gerencia:'CONSULTORÍA JURÍDICA', piso:'2', oficina:'2-02', cargo:'Asesor Especialista'},
];

/* Busca por nombre exacto, sin distinguir mayúsculas ni espacios de sobra. */
function directorioBuscar(nombre){
  const n = String(nombre || '').trim().toLowerCase().replace(/\s+/g, ' ');
  if(!n) return null;
  return DIRECTORIO.find(p => p.nombre.toLowerCase() === n) || null;
}
