/* ---------- Directorio de la casa ----------
   Quién trabaja dónde. Sale de "Listado General correos activos", el corte de
   personal del CIIP que maneja GTIC, con 176 personas (177 filas del listado,
   menos una duplicada por error de captura).

   Solo el CIIP. Marca País no viene en este corte, así que sus ~50 personas
   que estaban en la versión anterior de este archivo se quedaron fuera: hoy
   no hay de dónde sacarlas actualizadas. Cuando llegue un corte de Marca País,
   se agregan aquí igual que estas.

   Sirve para que nadie escriba su gerencia ni su cargo: escribe su nombre, se
   elige de la lista y el resto se llena solo.

   NO LLEVA CÉDULA, a propósito. La versión anterior sí la llevaba, con esta
   nota: "vale mientras esto viva en la red interna; el día que el sitio salga
   a internet, esta columna hay que sacarla". El sitio ya salió a internet
   (https://soporte-ciip.vercel.app, público, sin clave), así que se saca
   ahora: la Hoja de Servicio sigue pudiendo llevar cédula, pero la escribe
   quien pide, no la sirve este archivo a cualquiera que abra la página.

   Tampoco lleva piso ni oficina: el listado de correos no los tiene. Quedan
   vacíos para las 176; quien los necesite los escribe a mano, como si no
   apareciera en la lista.

   No lleva correo ni contraseña, ni falta que hacen aquí: ese listado es para
   las cuentas de correo institucional, no para pedir soporte, y una de esas
   dos cosas sí puede vivir en un archivo que el navegador de cualquiera
   descarga sin clave — la otra, nunca.
   Prefijo: DIRECTORIO. */
const DIRECTORIO = [
  {nombre:'Adrian Enrique Figueroa Barrios', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Aimee Estefania Ruiz Galavis', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Airuth del Valle Irazabal Hurtado', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Alcides Alejandro Robles Gordillo', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Alejandro Enrique Puglia Costas', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Presidente'},
  {nombre:'Alexander Daniel Blanco Ladino', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Alfredo Antonio Carrera Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Amarielys Gisel Gonzalez Muñoz', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Ana Maria Arraiz de Conde', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Ana Maria Villarroel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Andry Jesus Tovar Cabrera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Andrymar Mileydys Arellano Olivier', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Angelica Maria Ramirez Arellano', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Anghela Jacqueline Andrius Dávila Márquez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Aquiles Augusto Figueroa Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Barbara Yaismely Petterson Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Barbara Yaneth Depablos Torres', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Bracho Angel', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Carlos Alberto Belisario Silva', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Carlos Alejandro Garcia Alvarez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Carlos Daniel Torres Rodriguez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Carlos Eduardo Barreto Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Galindo Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Carlos Eduardo Perea Rangel', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carlos Enrique Manzano Kossik', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Carlos Manuel Rodriguez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carmen Oviedo Urrutia', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Carolina Forgione Franco', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Carolina Isabel Vargas Julio', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Chuaima Felipe Salas Camacho', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Dailyn Alejandra Romero Ardiles', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Dan Keisdert Moreno', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Danger Luis Rivero Ruiz', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Daniel Alberto Yepes Rivas', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Danna Alexandra Burguillos Díaz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Danny Joel Aponte Aponte', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Danyil Rafael Lugo Celis', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Deiber Jose Francisco Sella Dominguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Deinyelbert Jocksaniel Rodriguez Sarmiento', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Desiree Alejandra Cordero Lobo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Diana Carolina Bracho Indriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Dilia Yamilet Serrano Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Divarlys Nakarith Ocando Faneyte', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Douglas Emilio Prin Pereira', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Eddy Yolanda Peña de Granado', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Edward Jhonny Gonzalez', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Elias Josue Martinez Luque', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Eliub Ricardo Solorzano Perez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Ellius Enrique Rios Hernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Elys Daniel Martinez Zambrano', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Emely Miraidy Garcia Osuna', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Emely Nazaret Escalona Correa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Ericka Dubraska Flores Acevedo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Fabiola de los Angeles Martinez Duque', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Especialista'},
  {nombre:'Felix Armando Arraiz Planchart', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Franciel Jesus Rodriguez Bernal', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Francy Yusney Rincon', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Franklin David Reyes Delgado', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Franklin Nayit Acosta Angarita', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Fravia Vanessa Marquez de Fernandez', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Frenddy Enrique Santana Buitriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Gabriel Ramon Reyes Rangel', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Gabriela Carolina de los Angeles Brito Gómez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Geraldyn de los Angeles Lopez Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'German Javier Gerardino Diaz', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Guillermo Alexander Torres', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Gustavo Jose Zuñiga', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Hector Jose Bravo Osuna', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Hedwing Jose Gutierrez Blanco', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Hernan Enrique Marcano Oberto', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Hilda Anais Newman Mijares', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Imari del Valle Vasquez Capote', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Isabel Maria Peñaranda', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Isbelis Marielys Perez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Isolimar Coromoto Sanchez Fernandez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Ivan Arley Llanos', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Jackelyn Josefina Bermejo', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Jesly Oriana Baez Macedo', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Jessica Erlynes Rodriguez Alvarez', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jesus Antonio Arellano Natera', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Jipson Jesus Granadillo Albarran', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Joel Roman Aguilar Castro', gerencia:'VICEPRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Johanna Betzabeth De Almada Nieves', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jojan Jose Valbuena Garcia', gerencia:'GERENCIA GENERAL DEL DESPACHO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Jonathan Avisai Morales Martínez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Jonathan George Urbina Fernandez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Jose Gregorio Hernández Villegas', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Jose Gregorio Muñoz Rodriguez', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Jose Manuel Barrios Riera', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Jose Rafael Olivares Rodriguez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Juber Anulfo Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Julmar Enrique Moron Vasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Karelys Juliett Sanchez Lopez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Karen de Jesus Perez Muñoz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Karla Rosibel Sierra Palacios', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:''},
  {nombre:'Katiuska Elizabeth Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Katiuska del Valle Diaz Yanez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Kristina Dugnas Sulcas', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Layla Anabery Gonzalez Varela', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Leomary Andreina Malave Moreno', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Loisbeth Mariana Corvos Arismendi', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Lord Yolindria Guacache Suarez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Lucia Sampaio Martins', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luigersy Enrique Correa Mendez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Luis Alberto Ortega', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luis Alejandro Flores Gonzalez', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Luis Leopoldo Narvaez Gonzalez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Luis Miguel Ferrer Belgoderi', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Luis Vicente Garcia Lamas', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Mairin Celeste Camacho Escobar', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Manuel Eduardo Rodriguez Pereira', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Marbelis Eva Davila Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Marco Antonio Magallanes Grillet', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Consultor Jurídico'},
  {nombre:'Maria Emilia Torres Bonten', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maria Fernanda Ruiz Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Maria Jose Hernandez Morales', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maria Patricia Ferreira Mendoza', gerencia:'PRESIDENCIA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Maria Pia Savoia Rojas', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Maria Rosana Rodriguez Guzman', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Maribella Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Mariela Andrea Curvelo Hernández', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Marienny Daniela Santos Gonzalez', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Marilin Andreina Nuñez Arraiz', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Marinel Luzey Colmenares Blanco', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Martin Rafael Jimenez Calvo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Marysabel Aguilar Peraza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Maurelys Estefani Gonzalez Mosquera', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Mazuris Jiraly Azocar Benitez', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Migdalia Isabel Sanz Vaamondes', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Miguel Angel Cardenas Yepez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Miguel Angel Espinoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Milagros de Jesus Torres Gonzalez', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Morella Carmona de Hernandez', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Nahiry de Jesus Alcina Velasquez', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Nancy del Carmen Tovar Sanchez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Nathalia Yusmairi Guillen Lopez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Nelly del Carmen Rios Deal', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Nelson Jose Berrios', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Noraima del Milagro Coy Parra', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Oriana Gabriela Reina Mayora', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Oriana Patricia Perez Cabello', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Orlando Jose Yanez Saez', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Certificado'},
  {nombre:'Rahelenys Josue Burgos Santaella', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Rayda Ysabel Vera Parra', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Auditor Interno'},
  {nombre:'Regulo Antonio Ramirez Yanez', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Renny Moises Poleo Gascon', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Ricardo Jesus La Cruz Garcia', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Romelis Maria Viña Garcia', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Ronnie Percak Mendoza', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Rosbely del Carmen Bracho Indriago', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Rosmary Mariana Pantoja Blanco', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Asistente Ejecutivo'},
  {nombre:'Samy Emerson Osuna Mendoza', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Saray Ailemar Verdu Aragot', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Saskia Catheryn Victoria Calderon Veliz', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Saudy Coromoto Contreras', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Solangel Nailyn Suinagas Rada', gerencia:'GERENCIA GENERAL DE PROYECTOS DE INVERSIÓN Y ACTIVOS', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Solisver Coromoto Urbaez de Sandoval', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Treizen Guanipa', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Veruska Vanessa Vizcaya Castillo', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Asesor Profesional'},
  {nombre:'Vicente Paul Castillo Castellanos', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Viviana Isabel Cuello Pino', gerencia:'GERENCIA GENERAL DE TECNOLOGÍA DE LA INFORMACIÓN Y COMUNICACIÓN', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Wilfredo Niebles Villasmil', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'William Alfredo Castillo Bolle', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Gerente General'},
  {nombre:'Xiomara Sandoval Narvaez', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Coordinador'},
  {nombre:'Yajaira Coromoto Pinto Diaz', gerencia:'GERENCIA GENERAL DE GESTIÓN HUMANA', piso:'', oficina:'', cargo:'Asesor Técnico'},
  {nombre:'Yarizmit Gheinsy Herrera Medina', gerencia:'AUDITORÍA INTERNA', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yelinet Alexandra Ibarra Isturiz', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Yelitza Yatzyl Armas Liendo', gerencia:'GERENCIA GENERAL DEL OBSERVATORIO VENEZOLANO ANTIBLOQUEO', piso:'', oficina:'', cargo:'Técnico'},
  {nombre:'Yenaida Fagundez Vera', gerencia:'GERENCIA GENERAL DE PLANIFICACIÓN Y PRESUPUESTO', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yender Yuhuare Mendoza', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero General'},
  {nombre:'Yeniffer del Carmen Betancourt', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Obrero Supervisor'},
  {nombre:'Yesenia Janerys Martinez Escalona', gerencia:'GERENCIA GENERAL DE GESTIÓN ADMINISTRATIVA', piso:'', oficina:'', cargo:'Gerente'},
  {nombre:'Yessica Carolina Gomez Solorzano', gerencia:'GERENCIA GENERAL DE GESTIÓN COMUNICACIONAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Yoliskar de los Angeles Diaz Velasquez', gerencia:'GERENCIA GENERAL DE PROMOCIÓN DE INVERSIONES', piso:'', oficina:'', cargo:'Profesional'},
  {nombre:'Yosmary Vanesa Valero Paredes', gerencia:'GERENCIA GENERAL DE SEGURIDAD INTEGRAL', piso:'', oficina:'', cargo:'Bachiller'},
  {nombre:'Yuraima Karina Martinez Diaz', gerencia:'CONSULTORÍA JURÍDICA', piso:'', oficina:'', cargo:'Asesor Especialista'},
];

/* Busca por nombre exacto, sin distinguir mayúsculas, espacios de sobra ni
   tildes: "Jesus" y "Jesús" son el mismo nombre mal tecleado, no dos personas
   distintas, así que exigirle la tilde exacta solo rompía el auto-completado
   sin evitar ningún homónimo real. Sigue siendo el nombre completo, letra por
   letra salvo el acento: no se adivina por parecido. */
function directorioBuscar(nombre){
  const limpiar = s => String(s || '').trim().toLowerCase().replace(/\s+/g, ' ')
    .normalize('NFD').replace(/\p{Diacritic}/gu, '');
  const n = limpiar(nombre);
  if(!n) return null;
  return DIRECTORIO.find(p => limpiar(p.nombre) === n) || null;
}
