-- =====================================================================
-- Solicitudes de soporte · GTIC · CIIP
-- Migración 11: el CIIP entra a correos_permitidos
-- Se pega en el SQL Editor de Supabase y se corre una sola vez, DESPUÉS
-- de esquema.sql y de las migraciones 01 a 10.
--
-- De dónde sale esto:
--
-- gtic.correos_permitidos solo tenía los correos de quien ya se había
-- registrado antes de que la cuenta fuera obligatoria (migración 03: "los
-- correos de GTIC que ya tienen cuenta entran solos en la lista"). El resto
-- del CIIP —172 personas— nunca pudo registrarse: por eso salía "Ese correo
-- no está autorizado" al intentar crear la cuenta. Esta migración los
-- agrega, del mismo "Listado General correos activos" que ya se usó para
-- js/directorio.js.
--
-- 176 personas en el listado, menos 4:
--   · Jesus Arellano y franklin ya están, con su Gmail (migración 06).
--   · Daniel Alberto Yepes Rivas no tenía correo en el listado — decía
--     "N/A". Falta conseguirle uno para poder agregarlo.
--   · Carolina Forgione Franco y Ana Maria Arraiz de Conde comparten el
--     mismo correo en el listado (c.forgione@ciip.com.ve) — un error de
--     captura de la casa, no de aquí. Solo se puede agregar una vez; queda
--     marcado abajo para que GTIC lo resuelva con quien administre el
--     correo institucional.
--
-- Cuatro correos traían un error de tipeo en el dominio —"ciip.cpm.ve",
-- "ciip.vom.ve", "ciip.com" sin el ".ve"— y se corrigieron a "ciip.com.ve",
-- que es el dominio real en las otras 168 filas: sin la corrección, esas
-- cuatro personas no habrían podido registrarse con su correo verdadero.
--
-- on conflict do nothing: a quien ya esté en la lista —por ejemplo, si se
-- agregó a mano por algún caso puntual— esta migración no lo toca.
-- =====================================================================

insert into gtic.correos_permitidos (correo, nombre) values
  ('a.figueroa@ciip.com.ve', 'Adrian Enrique Figueroa Barrios'),
  ('a.ruiz@ciip.com.ve', 'Aimee Estefania Ruiz Galavis'),
  ('a.irazabal@ciip.com.ve', 'Airuth del Valle Irazabal Hurtado'),
  ('a.robles@ciip.com.ve', 'Alcides Alejandro Robles Gordillo'),
  ('a.costas@ciip.com.ve', 'Alejandro Enrique Puglia Costas'),
  ('a.blanco@ciip.com.ve', 'Alexander Daniel Blanco Ladino'),
  ('a.carrera@ciip.com.ve', 'Alfredo Antonio Carrera Perez'),
  ('a.gonzalez@ciip.com.ve', 'Amarielys Gisel Gonzalez Muñoz'),
  ('c.forgione@ciip.com.ve', 'Correo duplicado en el listado -- revisar con IT: Ana Maria Arraiz de Conde o Carolina Forgione Franco'),
  ('a.villaroel@ciip.com.ve', 'Ana Maria Villarroel'),
  ('a.tovar@ciip.com.ve', 'Andry Jesus Tovar Cabrera'),
  ('a.arellano@ciip.com.ve', 'Andrymar Mileydys Arellano Olivier'),
  ('a.ramirez@ciip.com.ve', 'Angelica Maria Ramirez Arellano'),
  ('a.davila@ciip.com.ve', 'Anghela Jacqueline Andrius Dávila Márquez'),
  ('aq.figueroa@ciip.com.ve', 'Aquiles Augusto Figueroa Mendoza'),
  ('b.petterson@ciip.com.ve', 'Barbara Yaismely Petterson Delgado'),
  ('b.depablos@ciip.com.ve', 'Barbara Yaneth Depablos Torres'),
  ('a.bracho@ciip.com.ve', 'Bracho Angel'),
  ('c.belisario@ciip.com.ve', 'Carlos Alberto Belisario Silva'),
  ('c.garcia@ciip.com.ve', 'Carlos Alejandro Garcia Alvarez'),
  ('ca.torres@ciip.com.ve', 'Carlos Daniel Torres Rodriguez'),
  ('c.barreto@ciip.com.ve', 'Carlos Eduardo Barreto Gonzalez'),
  ('c.galindo@ciip.com.ve', 'Carlos Eduardo Galindo Suarez'),
  ('c.perea@ciip.com.ve', 'Carlos Eduardo Perea Rangel'),
  ('c.manzano@ciip.com.ve', 'Carlos Enrique Manzano Kossik'),
  ('c.rodriguez@ciip.com.ve', 'Carlos Manuel Rodriguez Lopez'),
  ('c.oviedo@ciip.com.ve', 'Carmen Oviedo Urrutia'),
  ('c.vargas@ciip.com.ve', 'Carolina Isabel Vargas Julio'),
  ('c.salas@ciip.com.ve', 'Chuaima Felipe Salas Camacho'),
  ('d.romero@ciip.com.ve', 'Dailyn Alejandra Romero Ardiles'),
  ('k.moreno@ciip.com.ve', 'Dan Keisdert Moreno'),
  ('d.rivero@ciip.com.ve', 'Danger Luis Rivero Ruiz'),
  ('d.burguillos@ciip.com.ve', 'Danna Alexandra Burguillos Díaz'),
  ('d.aponte@ciip.com.ve', 'Danny Joel Aponte Aponte'),
  ('d.lugo@ciip.com.ve', 'Danyil Rafael Lugo Celis'),
  ('j.sella@ciip.com.ve', 'Deiber Jose Francisco Sella Dominguez'),
  ('d.rodriguez@ciip.com.ve', 'Deinyelbert Jocksaniel Rodriguez Sarmiento'),
  ('d.cordero@ciip.com.ve', 'Desiree Alejandra Cordero Lobo'),
  ('d.bracho@ciip.com.ve', 'Diana Carolina Bracho Indriago'),
  ('d.serrano@ciip.com.ve', 'Dilia Yamilet Serrano Perez'),
  ('d.ocando@ciip.com.ve', 'Divarlys Nakarith Ocando Faneyte'),
  ('d.prin@ciip.com.ve', 'Douglas Emilio Prin Pereira'),
  ('e.pena@ciip.com.ve', 'Eddy Yolanda Peña de Granado'),
  ('e.gonzalez@ciip.com.ve', 'Edward Jhonny Gonzalez'),
  ('e.luque@ciip.com.ve', 'Elias Josue Martinez Luque'),
  ('e.solorzano@ciip.com.ve', 'Eliub Ricardo Solorzano Perez'),
  ('e.rios@ciip.com.ve', 'Ellius Enrique Rios Hernandez'),
  ('e.martinez@ciip.com.ve', 'Elys Daniel Martinez Zambrano'),
  ('em.garcia@ciip.com.ve', 'Emely Miraidy Garcia Osuna'),
  ('e.escalona@ciip.com.ve', 'Emely Nazaret Escalona Correa'),
  ('e.flores@ciip.com.ve', 'Ericka Dubraska Flores Acevedo'),
  ('f.martinez@ciip.com.ve', 'Fabiola de los Angeles Martinez Duque'),
  ('f.arraiz@ciip.com.ve', 'Felix Armando Arraiz Planchart'),
  ('f.rodriguez@ciip.com.ve', 'Franciel Jesus Rodriguez Bernal'),
  ('f.rincon@ciip.com.ve', 'Francy Yusney Rincon'),
  ('f.acosta@ciip.com.ve', 'Franklin Nayit Acosta Angarita'),
  ('f.marquez@ciip.com.ve', 'Fravia Vanessa Marquez de Fernandez'),
  ('f.santana@ciip.com.ve', 'Frenddy Enrique Santana Buitriago'),
  ('g.reyes@ciip.com.ve', 'Gabriel Ramon Reyes Rangel'),
  ('g.brito@ciip.com.ve', 'Gabriela Carolina de los Angeles Brito Gómez'),
  ('g.lopez@ciip.com.ve', 'Geraldyn de los Angeles Lopez Rojas'),
  ('g.gerardino@ciip.com.ve', 'German Javier Gerardino Diaz'),
  ('g.torres@ciip.com.ve', 'Guillermo Alexander Torres'),
  ('g.zuniga@ciip.com.ve', 'Gustavo Jose Zuñiga'),
  ('h.bravo@ciip.com.ve', 'Hector Jose Bravo Osuna'),
  ('h.gutierrez@ciip.com.ve', 'Hedwing Jose Gutierrez Blanco'),
  ('o.marcano@ciip.com.ve', 'Hernan Enrique Marcano Oberto'),
  ('h.newman@ciip.com.ve', 'Hilda Anais Newman Mijares'),
  ('i.vasquez@ciip.com.ve', 'Imari del Valle Vasquez Capote'),
  ('i.penaranda@ciip.com.ve', 'Isabel Maria Peñaranda'),
  ('i.perez@ciip.com.ve', 'Isbelis Marielys Perez'),
  ('i.sanchez@ciip.com.ve', 'Isolimar Coromoto Sanchez Fernandez'),
  ('i.llanos@ciip.com.ve', 'Ivan Arley Llanos'),
  ('j.bermejo@ciip.com.ve', 'Jackelyn Josefina Bermejo'),
  ('j.baez@ciip.com.ve', 'Jesly Oriana Baez Macedo'),
  ('j.rodriguez@ciip.com.ve', 'Jessica Erlynes Rodriguez Alvarez'),
  ('j.granadillo@ciip.com.ve', 'Jipson Jesus Granadillo Albarran'),
  ('j.aguilar@ciip.com.ve', 'Joel Roman Aguilar Castro'),
  ('j.dealmada@ciip.com.ve', 'Johanna Betzabeth De Almada Nieves'),
  ('j.valbuena@ciip.com.ve', 'Jojan Jose Valbuena Garcia'),
  ('j.morales@ciip.com.ve', 'Jonathan Avisai Morales Martínez'),
  ('j.urbina@ciip.com.ve', 'Jonathan George Urbina Fernandez'),
  ('j.hernandez@ciip.com.ve', 'Jose Gregorio Hernández Villegas'),
  ('j.munoz@ciip.com.ve', 'Jose Gregorio Muñoz Rodriguez'),
  ('j.barrios@ciip.com.ve', 'Jose Manuel Barrios Riera'),
  ('j.olivares@ciip.com.ve', 'Jose Rafael Olivares Rodriguez'),
  ('j.mendoza@ciip.com.ve', 'Juber Anulfo Mendoza'),
  ('j.moron@ciip.com.ve', 'Julmar Enrique Moron Vasquez'),
  ('kj.sanchez@ciip.com.ve', 'Karelys Juliett Sanchez Lopez'),
  ('k.perez@ciip.com.ve', 'Karen de Jesus Perez Muñoz'),
  ('k.sierra@ciip.com.ve', 'Karla Rosibel Sierra Palacios'),
  ('k.sanchez@ciip.com.ve', 'Katiuska Elizabeth Sanchez'),
  ('k.diaz@ciip.com.ve', 'Katiuska del Valle Diaz Yanez'),
  ('k.sulcas@ciip.com.ve', 'Kristina Dugnas Sulcas'),
  ('l.varela@ciip.com.ve', 'Layla Anabery Gonzalez Varela'),
  ('l.malave@ciip.com.ve', 'Leomary Andreina Malave Moreno'),
  ('l.corvos@ciip.com.ve', 'Loisbeth Mariana Corvos Arismendi'),
  ('l.guacache@ciip.com.ve', 'Lord Yolindria Guacache Suarez'),
  ('l.sampaio@ciip.com.ve', 'Lucia Sampaio Martins'),
  ('l.correa@ciip.com.ve', 'Luigersy Enrique Correa Mendez'),
  ('l.ortega@ciip.com.ve', 'Luis Alberto Ortega'),
  ('l.flores@ciip.com.ve', 'Luis Alejandro Flores Gonzalez'),
  ('l.narvaez@ciip.com.ve', 'Luis Leopoldo Narvaez Gonzalez'),
  ('l.ferrer@ciip.com.ve', 'Luis Miguel Ferrer Belgoderi'),
  ('l.lamas@ciip.com.ve', 'Luis Vicente Garcia Lamas'),
  ('m.camacho@ciip.com.ve', 'Mairin Celeste Camacho Escobar'),
  ('m.rodriguez@ciip.com.ve', 'Manuel Eduardo Rodriguez Pereira'),
  ('m.davila@ciip.com.ve', 'Marbelis Eva Davila Santaella'),
  ('m.magallanes@ciip.com.ve', 'Marco Antonio Magallanes Grillet'),
  ('m.bonten@ciip.com.ve', 'Maria Emilia Torres Bonten'),
  ('m.ruiz@ciip.com.ve', 'Maria Fernanda Ruiz Gonzalez'),
  ('m.hernandez@ciip.com.ve', 'Maria Jose Hernandez Morales'),
  ('p.ferreira@ciip.com.ve', 'Maria Patricia Ferreira Mendoza'),
  ('m.savoia@ciip.com.ve', 'Maria Pia Savoia Rojas'),
  ('mr.rodriguez@ciip.com.ve', 'Maria Rosana Rodriguez Guzman'),
  ('m.aguilar@ciip.com.ve', 'Maribella Aguilar Peraza'),
  ('m.curvelo@ciip.com.ve', 'Mariela Andrea Curvelo Hernández'),
  ('m.santos@ciip.com.ve', 'Marienny Daniela Santos Gonzalez'),
  ('m.nunez@ciip.com.ve', 'Marilin Andreina Nuñez Arraiz'),
  ('m.colmenares@ciip.com.ve', 'Marinel Luzey Colmenares Blanco'),
  ('m.jimenez@ciip.com.ve', 'Martin Rafael Jimenez Calvo'),
  ('ma.aguilar@ciip.com.ve', 'Marysabel Aguilar Peraza'),
  ('m.gonzalez@ciip.com.ve', 'Maurelys Estefani Gonzalez Mosquera'),
  ('m.azocar@ciip.com.ve', 'Mazuris Jiraly Azocar Benitez'),
  ('m.sanz@ciip.com.ve', 'Migdalia Isabel Sanz Vaamondes'),
  ('m.cardenas@ciip.com.ve', 'Miguel Angel Cardenas Yepez'),
  ('m.espinoza@ciip.com.ve', 'Miguel Angel Espinoza'),
  ('m.torre@ciip.com.ve', 'Milagros de Jesus Torres Gonzalez'),
  ('mc.gonzalez@ciip.com.ve', 'Morella Carmona de Hernandez'),
  ('n.alcina@ciip.com.ve', 'Nahiry de Jesus Alcina Velasquez'),
  ('n.tovar@ciip.com.ve', 'Nancy del Carmen Tovar Sanchez'),
  ('n.guillen@ciip.com.ve', 'Nathalia Yusmairi Guillen Lopez'),
  ('n.rios@ciip.com.ve', 'Nelly del Carmen Rios Deal'),
  ('n.berrios@ciip.com.ve', 'Nelson Jose Berrios'),
  ('n.coy@ciip.com.ve', 'Noraima del Milagro Coy Parra'),
  ('o.reina@ciip.com.ve', 'Oriana Gabriela Reina Mayora'),
  ('o.perez@ciip.com.ve', 'Oriana Patricia Perez Cabello'),
  ('o.yanez@ciip.com.ve', 'Orlando Jose Yanez Saez'),
  ('r.burgos@ciip.com.ve', 'Rahelenys Josue Burgos Santaella'),
  ('r.vera@ciip.com.ve', 'Rayda Ysabel Vera Parra'),
  ('r.ramirez@ciip.com.ve', 'Regulo Antonio Ramirez Yanez'),
  ('r.poleo@ciip.com.ve', 'Renny Moises Poleo Gascon'),
  ('r.lacruz@ciip.com.ve', 'Ricardo Jesus La Cruz Garcia'),
  ('r.vina@ciip.com.ve', 'Romelis Maria Viña Garcia'),
  ('r.percak@ciip.com.ve', 'Ronnie Percak Mendoza'),
  ('r.godoy@ciip.com.ve', 'Rosbely del Carmen Bracho Indriago'),
  ('r.pantoja@ciip.com.ve', 'Rosmary Mariana Pantoja Blanco'),
  ('s.osuna@ciip.com.ve', 'Samy Emerson Osuna Mendoza'),
  ('s.verdu@ciip.com.ve', 'Saray Ailemar Verdu Aragot'),
  ('s.calderon@ciip.com.ve', 'Saskia Catheryn Victoria Calderon Veliz'),
  ('s.contreras@ciip.com.ve', 'Saudy Coromoto Contreras'),
  ('s.suinagas@ciip.com.ve', 'Solangel Nailyn Suinagas Rada'),
  ('s.urbaez@ciip.com.ve', 'Solisver Coromoto Urbaez de Sandoval'),
  ('t.guanipa@ciip.com.ve', 'Treizen Guanipa'),
  ('v.vizcaya@ciip.com.ve', 'Veruska Vanessa Vizcaya Castillo'),
  ('v.castillo@ciip.com.ve', 'Vicente Paul Castillo Castellanos'),
  ('v.cuello@ciip.com.ve', 'Viviana Isabel Cuello Pino'),
  ('w.niebles@ciip.com.ve', 'Wilfredo Niebles Villasmil'),
  ('w.castillo@ciip.com.ve', 'William Alfredo Castillo Bolle'),
  ('x.sandoval@ciip.com.ve', 'Xiomara Sandoval Narvaez'),
  ('y.pinto@ciip.com.ve', 'Yajaira Coromoto Pinto Diaz'),
  ('y.herrera@ciip.com.ve', 'Yarizmit Gheinsy Herrera Medina'),
  ('y.ibarra@ciip.com.ve', 'Yelinet Alexandra Ibarra Isturiz'),
  ('y.armas@ciip.com.ve', 'Yelitza Yatzyl Armas Liendo'),
  ('y.fagundez@ciip.com.ve', 'Yenaida Fagundez Vera'),
  ('y.mendoza@ciip.com.ve', 'Yender Yuhuare Mendoza'),
  ('y.betancourt@ciip.com.ve', 'Yeniffer del Carmen Betancourt'),
  ('ye.martinez@ciip.com.ve', 'Yesenia Janerys Martinez Escalona'),
  ('y.gomez@ciip.com.ve', 'Yessica Carolina Gomez Solorzano'),
  ('y.diaz@ciip.com.ve', 'Yoliskar de los Angeles Diaz Velasquez'),
  ('y.valero@ciip.com.ve', 'Yosmary Vanesa Valero Paredes'),
  ('y.martinez@ciip.com.ve', 'Yuraima Karina Martinez Diaz')
on conflict (correo) do nothing;
